### ISSUE TITLE
Rental Information is not Shown when `rview` is Executed

### ISSUE THREAD

**Issue by RobotWizzard** [AY2425S1-CS2103T-T15-1/tp#195]
When the `rview` command is executed on a client with rental information, no rental information is shown on the right list panel. A `NullPointerException` is thrown.

---

![image](https://github.com/user-attachments/assets/b9fdd45c-4644-4adc-a674-8a2bac84c624)

```java
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at seedu.address.ui.UiPart.getFxmlFileUrl(UiPart.java:85)
	at seedu.address.ui.UiPart.<init>(UiPart.java:35)
	at seedu.address.ui.RentalInformationListCard.<init>(RentalInformationListCard.java:51)
	at seedu.address.ui.RentalInformationListPanel$RentalInformationListViewCell.updateItem(RentalInformationListPanel.java:90)
	at seedu.address.ui.RentalInformationListPanel$RentalInformationListViewCell.updateItem(RentalInformationListPanel.java:81)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:481)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1804)
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1788)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3030)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3002)
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3090)
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3073)
	at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:860)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:904)
	at javafx.scene.control.skin.ListViewSkin.updateItemCount(ListViewSkin.java:357)
	at javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:184)
	at javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:159)
	at javafx.scene.control.skin.ListViewSkin.layoutChildren(ListViewSkin.java:300)
	at javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2515)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:423)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:422)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:452)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by RobotWizzard** [comment]
This bug is caused by the name of `RentalInformationCard.fxml`. `RentalInformationListCard.java` tries to find a file named `RentalInformationListCard.fxml` but is unable to find it. 

![image](https://github.com/user-attachments/assets/f67a3409-f6d3-4c0a-9a7c-05f7e956fdbe)
